In [1]:
import tensorflow as tf

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
import warnings
from sklearn.metrics import accuracy_score
warnings.filterwarnings('ignore')

path = r"C:\Users\Administrator\Desktop\Folders\Term-3\AI\Dataset"
os.chdir(path)
data = pd.read_csv("data.csv")
data.head()

label      x1      x2
0      1  2.6487  4.5192
1      1  1.5438  2.4443
2      1  1.8990  4.2409
3      1  2.4711  5.8097
4      1  3.3590  6.4423

In [2]:
#defining the perceptron

#define placeholder for features and labels
X_input =data[['x1','x2']]

Y_label = data[['label']]

In [3]:
#define placeholder for features and labels
x = tf.placeholder(tf.float32,[None,2]) # inputs/features -x1, x2
#Labels
y = tf.placeholder(tf.float32,[None,1]) #Labels


# weights and bias -layer 1
weight = tf.Variable(tf.truncated_normal([2,100], stddev=0.1))

bias = tf.Variable(tf.truncated_normal([100], stddev=0.1))

#input function

netinput = tf.add(tf.matmul(x,weight), bias)

#activation function

output = tf.nn.relu(netinput)

In [4]:
# weights and bias -layer 2
weight2 = tf.Variable(tf.truncated_normal([100,150], stddev=0.1))

bias2 = tf.Variable(tf.truncated_normal([150], stddev=0.1))

#input function

netinput2 = tf.add(tf.matmul(output,weight2), bias2)

#activation function

output2 = tf.nn.relu(netinput2)

In [5]:
# weights and bias -layer 3
weight3 = tf.Variable(tf.truncated_normal([150,1], stddev=0.1))

bias3 = tf.Variable(tf.truncated_normal([1], stddev=0.1))

#input function

netinput3 = tf.add(tf.matmul(output2,weight3), bias3)

#activation function

output3 = tf.sigmoid(netinput3)

In [6]:
#define the cost or loss function amd the optimizier

loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=output3))

gdo = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = gdo.minimize(loss)

#initialize the variables

init = tf.global_variables_initializer()

In [7]:
sess = tf.Session()
sess.run(init)
#sess.run(train)

In [8]:
for i in range(1000):
    final_train = sess.run(train, feed_dict={x:X_input, y:Y_label})

In [9]:
result = sess.run(output3,feed_dict={x:X_input})

result

array([[0.8347781 ],
       [0.6907125 ],
       [0.872318  ],
       [0.925199  ],
       [0.9343929 ],
       [0.9041403 ],
       [0.8924965 ],
       [0.85788226],
       [0.93710166],
       [0.00514708],
       [0.00308868],
       [0.00432508],
       [0.01222   ],
       [0.01082278],
       [0.05546884],
       [0.0808047 ],
       [0.04432357],
       [0.04589849],
       [0.06462591],
       [0.00252655],
       [0.00403528]], dtype=float32)

In [10]:
y_pred = result.round()

y_pred

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [11]:
accuracy_score(Y_label, y_pred)

1.0

In [12]:
confusion_matrix(Y_label, y_pred)

array([[12,  0],
       [ 0,  9]], dtype=int64)