In [1]:
import tensorflow as tf


In [2]:
const1 = tf.constant(10)
print(const1)

Tensor("Const:0", shape=(), dtype=int32)


In [3]:
var1 = tf.Variable(100)
var1

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [4]:
mysum = tf.add(const1,var1)

In [5]:
mysum

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [6]:
product = tf.multiply(var1, mysum)

In [7]:
var1 = mysum

In [8]:
var1

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [9]:
#you need this when using Variables only
#if you are using constants and placeholders - you do need this line of code

init_op =tf.global_variables_initializer()

In [10]:
sess = tf.Session()

In [11]:
sess.run(const1)

10

In [12]:
sess.run(init_op)

In [13]:
print(sess.run(var1))

110


In [14]:
print(sess.run(mysum))

110


In [15]:
print(sess.run(product))

11000


=======================================================Placeholder=========================================================

In [16]:
a = tf.placeholder(tf.float32)

In [17]:
b = a*2

In [18]:
#sess.run(b)

In [19]:
sess.run(b, feed_dict={a:3.0})

6.0

In [20]:
sess.run(b, feed_dict={a:[1,2,3,4]})

array([2., 4., 6., 8.], dtype=float32)

In [21]:
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],
                 [16,17,18],[19,20,21],[22,23,24]]]}

In [22]:
result = sess.run(b, feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]
  [26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [23]:
sess.run(b, feed_dict=dictionary)

array([[[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.],
        [20., 22., 24.],
        [26., 28., 30.],
        [32., 34., 36.],
        [38., 40., 42.],
        [44., 46., 48.]]], dtype=float32)

In [24]:
sess.close()