In [1]:
import tensorflow as tf

import os
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
import warnings
from sklearn.metrics import accuracy_score
warnings.filterwarnings('ignore')

path = r"C:\Users\Administrator\Desktop\Folders\Term-3\AI\Dataset"
os.chdir(path)
data = pd.read_csv("sonar.csv")
data.head()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0       0.0200       0.0371       0.0428       0.0207       0.0954   
1       0.0453       0.0523       0.0843       0.0689       0.1183   
2       0.0262       0.0582       0.1099       0.1083       0.0974   
3       0.0100       0.0171       0.0623       0.0205       0.0205   
4       0.0762       0.0666       0.0481       0.0394       0.0590   

   attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0       0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1       0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2       0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3       0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4       0.0649       0.1209       0.2467       0.3564        0.4459  ...   

   attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0        0.0027        0.0065        0.0159        0.0072        0.0167   
1        0.0084        0.0089        0.0048        0.0094        0.0191   
2        0.0232        0.0166        0.0095        0.0180        0.0244   
3        0.0121        0.0036        0.0150        0.0085        0.0073   
4        0.0031        0.0054        0.0105        0.0110        0.0015   

   attribute_57  attribute_58  attribute_59  attribute_60  Class  
0        0.0180        0.0084        0.0090        0.0032   Rock  
1        0.0140        0.0049        0.0052        0.0044   Rock  
2        0.0316        0.0164        0.0095        0.0078   Rock  
3        0.0050        0.0044        0.0040        0.0117   Rock  
4        0.0072        0.0048        0.0107        0.0094   Rock  

[5 rows x 61 columns]

In [2]:
dict_1 = {'Rock': 0,'Mine': 1} 
data.Class = [dict_1[item] for item in data.Class] 

def rename(val):
    if val == 'Rock':
        return 0
    else:
        return 1
    
data['Label'] = data['Class'].apply(rename)

In [3]:
data.head()

attribute_1  attribute_2  attribute_3  attribute_4  attribute_5  \
0       0.0200       0.0371       0.0428       0.0207       0.0954   
1       0.0453       0.0523       0.0843       0.0689       0.1183   
2       0.0262       0.0582       0.1099       0.1083       0.0974   
3       0.0100       0.0171       0.0623       0.0205       0.0205   
4       0.0762       0.0666       0.0481       0.0394       0.0590   

   attribute_6  attribute_7  attribute_8  attribute_9  attribute_10  ...  \
0       0.0986       0.1539       0.1601       0.3109        0.2111  ...   
1       0.2583       0.2156       0.3481       0.3337        0.2872  ...   
2       0.2280       0.2431       0.3771       0.5598        0.6194  ...   
3       0.0368       0.1098       0.1276       0.0598        0.1264  ...   
4       0.0649       0.1209       0.2467       0.3564        0.4459  ...   

   attribute_52  attribute_53  attribute_54  attribute_55  attribute_56  \
0        0.0027        0.0065        0.0159        0.0072        0.0167   
1        0.0084        0.0089        0.0048        0.0094        0.0191   
2        0.0232        0.0166        0.0095        0.0180        0.0244   
3        0.0121        0.0036        0.0150        0.0085        0.0073   
4        0.0031        0.0054        0.0105        0.0110        0.0015   

   attribute_57  attribute_58  attribute_59  attribute_60  Class  
0        0.0180        0.0084        0.0090        0.0032      0  
1        0.0140        0.0049        0.0052        0.0044      0  
2        0.0316        0.0164        0.0095        0.0078      0  
3        0.0050        0.0044        0.0040        0.0117      0  
4        0.0072        0.0048        0.0107        0.0094      0  

[5 rows x 61 columns]

In [4]:
#defining the perceptron

#define placeholder for features and labels
X_input = data[data.columns.difference(['Class'])]

Y_label = data[['Class']]

In [5]:
Y_label.head()

Class
0      0
1      0
2      0
3      0
4      0

In [6]:
X_input.shape

(208, 60)

In [7]:
data.shape

(208, 61)

In [8]:
#define placeholder for features and labels
x = tf.placeholder(tf.float32,[None,60]) # inputs/features -x1, x2
#Labels
y = tf.placeholder(tf.float32,[None,1]) #Labels


# weights and bias
weight = tf.Variable(tf.zeros([60,1]))

bias = tf.Variable(tf.zeros([1]))

#input function

I = tf.add(tf.matmul(x,weight), bias)

#activation function

output = tf.sigmoid(I)

In [9]:
#define the cost or loss function amd the optimizier

individual_loss = tf.nn.sigmoid_cross_entropy_with_logits(labels=y, logits=output)
loss = tf.reduce_mean(individual_loss)

gdo = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = gdo.minimize(loss)

#initialize the variables

init = tf.global_variables_initializer()

In [10]:
sess = tf.Session()
sess.run(init)

In [11]:
sess.run(bias)

array([0.], dtype=float32)

In [12]:
for i in range(550000):
    final_train = sess.run(train, feed_dict={x:X_input, y:Y_label})

In [13]:
sess.run(bias)

array([-5.774121], dtype=float32)

In [14]:
result = sess.run(output,feed_dict={x:X_input})

result

array([[3.31167787e-01],
       [2.51149744e-01],
       [9.99217629e-01],
       [2.54358113e-01],
       [7.81306028e-01],
       [1.30818002e-02],
       [3.48689444e-02],
       [9.95460927e-01],
       [9.62292969e-01],
       [2.85139710e-01],
       [4.66453988e-04],
       [1.79807037e-01],
       [8.47512782e-02],
       [8.62532761e-03],
       [1.50313437e-01],
       [1.33904326e-03],
       [1.27775654e-01],
       [2.52164397e-02],
       [3.74822237e-04],
       [9.99642968e-01],
       [5.57389021e-01],
       [7.49007845e-03],
       [9.97901186e-02],
       [4.87185875e-03],
       [4.47723069e-05],
       [8.97002872e-03],
       [1.99063227e-01],
       [4.96818088e-02],
       [2.63026744e-01],
       [6.90411747e-01],
       [1.23163663e-01],
       [4.81072254e-03],
       [3.39825428e-03],
       [1.50375932e-01],
       [6.87489063e-02],
       [6.76567078e-01],
       [4.99979779e-03],
       [4.26785741e-03],
       [2.73330533e-03],
       [2.68457830e-03],


In [15]:
y_pred = result.round()

y_pred

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [16]:
accuracy_score(Y_label,y_pred)

0.8605769230769231

In [17]:
confusion_matrix(Y_label, y_pred)

array([[89,  8],
       [21, 90]], dtype=int64)