In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable([2,50,3,10,4,5,6,7])

In [3]:
y = tf.Variable([[1,2],[3,4],[5,6]])

In [4]:
z = tf.Variable([[1,9],[8,2],[8,7]])

In [5]:
sess =tf.Session()

In [6]:
initop = tf.global_variables_initializer()

In [7]:
sess.run(initop)

In [8]:
sess.run(x)

array([ 2, 50,  3, 10,  4,  5,  6,  7])

In [9]:
sess.run(y)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
sess.run(z)

array([[1, 9],
       [8, 2],
       [8, 7]])

In [11]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

# Reshape

In [12]:
sess.run(tf.reshape(y,[2,3]))

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

In [14]:
z.shape

TensorShape([Dimension(3), Dimension(2)])

In [15]:
sess.run(tf.argmax(z, axis=0))

array([1, 0], dtype=int64)

In [16]:
sess.run(tf.argmax(z, axis=1))

array([1, 0, 0], dtype=int64)

In [17]:
sess.close()