In [7]:
import tensorflow as tf

import os
import numpy as np
import pandas as pd 
from pandas import get_dummies
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
import warnings
from sklearn.metrics import accuracy_score
warnings.filterwarnings('ignore')

from sklearn.datasets import load_iris

path = r"C:\Users\Administrator\Desktop\Folders\Term-3\AI\Dataset"
os.chdir(path)
data = pd.read_csv("Iris_dataset.csv")
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
X_input = data.drop(labels='Species', axis=1)

Y_label = data.iloc[:,4]

In [10]:
y_dummies = pd.get_dummies(Y_label)

y_hot = y_dummies.values

In [12]:
#defining the perceptron

#define placeholder for features and labels
x = tf.placeholder(tf.float32,[None,4])

y = tf.placeholder(tf.float32,[None,3])


#weights and bias

weight = tf.Variable(tf.truncated_normal([4,3],stddev=0.1))

bias = tf.Variable(tf.truncated_normal([1],stddev=0.1))

#input function

netinput = tf.add(tf.matmul(x,weight), bias)

#activation function

output = tf.nn.softmax(netinput)

In [13]:
#define the cost or loss function amd the optimizier

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=output))


#Optimizer
gdo = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = gdo.minimize(loss)

#initialize the variables

init = tf.global_variables_initializer()

In [15]:
sess = tf.Session()
sess.run(init)

In [17]:
for i in range(5000):
    final_train = sess.run(train, feed_dict={x:X_input, y:y_hot})

In [18]:
predict = sess.run(output, feed_dict={x:X_input})

predict

array([[9.68810022e-01, 3.11626829e-02, 2.74067643e-05],
       [9.34108496e-01, 6.57813996e-02, 1.10138368e-04],
       [9.57073450e-01, 4.28569093e-02, 6.96540010e-05],
       [9.28942502e-01, 7.08587393e-02, 1.98792783e-04],
       [9.72632587e-01, 2.73416247e-02, 2.57461561e-05],
       [9.69869375e-01, 3.01001724e-02, 3.03622837e-05],
       [9.59845126e-01, 4.00635973e-02, 9.12348478e-05],
       [9.56318617e-01, 4.36253212e-02, 5.60795161e-05],
       [9.18393612e-01, 8.13104734e-02, 2.95882579e-04],
       [9.34043884e-01, 6.58544898e-02, 1.01657977e-04],
       [9.73427773e-01, 2.65565421e-02, 1.56421083e-05],
       [9.46383953e-01, 5.35084940e-02, 1.07645305e-04],
       [9.35086668e-01, 6.48084879e-02, 1.04845640e-04],
       [9.58454549e-01, 4.14630212e-02, 8.23244991e-05],
       [9.90671039e-01, 9.32742655e-03, 1.52835673e-06],
       [9.90416765e-01, 9.58011858e-03, 3.16163187e-06],
       [9.85300720e-01, 1.46915810e-02, 7.61860247e-06],
       [9.67834294e-01, 3.21320

In [19]:
result = sess.run(tf.arg_max(predict,1))

result

Instructions for updating:
Use `argmax` instead


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [20]:
labhot = sess.run(tf.arg_max(y_hot,1))

labhot

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [21]:
accuracy_score(result,labhot)

0.9666666666666667

In [22]:
confusion_matrix(result,labhot)

array([[50,  0,  0],
       [ 0, 45,  0],
       [ 0,  5, 50]], dtype=int64)