In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable([[1,2,3],[4,5,6]])

In [3]:
y = tf.Variable([[7,8,9],[10,11,12]])

In [4]:
init_op = tf.global_variables_initializer()

In [5]:
sess = tf.Session()

In [6]:
sess.run(init_op)

In [7]:
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32_ref>

In [8]:
print(sess.run(y))

[[ 7  8  9]
 [10 11 12]]


In [9]:
c1 = tf.multiply(x,y)

In [10]:
sess.run(c1)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [11]:
c2 = tf.multiply(y,x)
sess.run(c2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [12]:
X = tf.placeholder(tf.int32)
Y = tf.placeholder(tf.int32)

In [13]:
sess.run(c2, feed_dict={X:([[1,2,3],[4,5,6]]), Y:([[7,8,9],[10,11,12]])})

array([[ 7, 16, 27],
       [40, 55, 72]])

In [15]:
sess.close()