In [1]:
import tensorflow as tf

import os
import numpy as np
import pandas as pd 
from pandas import get_dummies
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
import warnings
from sklearn.metrics import accuracy_score
warnings.filterwarnings('ignore')

from sklearn.datasets import load_iris

path = r"C:\Users\Administrator\Desktop\Folders\Term-3\AI\Dataset"
os.chdir(path)
data = pd.read_csv("Iris_dataset.csv")
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
X_input = data.drop(labels='Species', axis=1)

Y_label = data[['Species']]

In [3]:
#defining the perceptron

#define placeholder for features and labels
x = tf.placeholder(tf.float32,[None,4])

y = tf.placeholder(tf.float32,[None,3])


# first hidden layer
W1 = tf.Variable(tf.truncated_normal([4,50],stddev=0.1))
b1 = tf.Variable(tf.truncated_normal([50]))

#output of first hidden layer
y1 = tf.nn.relu(tf.matmul(x,W1) + b1)

In [4]:
y_dummies = pd.get_dummies(Y_label)

y_hot = y_dummies.values

In [5]:
# second hidden layer
W2 = tf.Variable(tf.truncated_normal([50,50],stddev=0.1))
b2 = tf.Variable(tf.truncated_normal([50]))

#output of second hidden layer
y2 = tf.nn.relu(tf.matmul(y1,W2) + b2)

In [6]:
# second hidden layer
W3 = tf.Variable(tf.truncated_normal([50,50],stddev=0.1))
b3 = tf.Variable(tf.truncated_normal([50]))

#output of second hidden layer
y3 = tf.nn.relu(tf.matmul(y1,W2) + b2)

In [7]:
# third hidden layer
# 3 because 3 possible class
W4 = tf.Variable(tf.truncated_normal([50,3],stddev=0.1))

b4 = tf.Variable(tf.truncated_normal([3]))

#Net input function of last layer ...without activation function
I = tf.matmul(y3,W4) + b4 

#activation function - Softmax
Output=tf.nn.softmax(I)

In [8]:
# Cross Entropy

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y_hot, logits=Output))

In [9]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.3)

In [10]:
train = optimizer.minimize(cross_entropy)

In [11]:
#Create Session

init = tf.global_variables_initializer()

sess=tf.Session()
sess.run(init)

In [12]:
for i in range(15000):
    final_train = sess.run(train, feed_dict={x:X_input, y:y_hot})

In [13]:
predict = sess.run(Output, feed_dict={x:X_input})

predict

array([[9.99999404e-01, 5.97216228e-07, 0.00000000e+00],
       [9.99992132e-01, 7.83898395e-06, 0.00000000e+00],
       [9.99997377e-01, 2.59925537e-06, 0.00000000e+00],
       [9.99989510e-01, 1.04975788e-05, 0.00000000e+00],
       [9.99999523e-01, 4.41382213e-07, 0.00000000e+00],
       [9.99999523e-01, 4.63645733e-07, 0.00000000e+00],
       [9.99997377e-01, 2.64623759e-06, 0.00000000e+00],
       [9.99998450e-01, 1.58885825e-06, 0.00000000e+00],
       [9.99976993e-01, 2.30447185e-05, 0.00000000e+00],
       [9.99994874e-01, 5.06699917e-06, 0.00000000e+00],
       [9.99999762e-01, 2.44669280e-07, 0.00000000e+00],
       [9.99996901e-01, 3.12729594e-06, 0.00000000e+00],
       [9.99993801e-01, 6.17919659e-06, 0.00000000e+00],
       [9.99996543e-01, 3.41983559e-06, 0.00000000e+00],
       [1.00000000e+00, 1.13216734e-08, 0.00000000e+00],
       [1.00000000e+00, 1.52346278e-08, 0.00000000e+00],
       [9.99999881e-01, 9.32330195e-08, 0.00000000e+00],
       [9.99999166e-01, 8.54650

In [14]:
result = sess.run(tf.arg_max(predict,1))

result

Instructions for updating:
Use `argmax` instead


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [15]:
labhot = sess.run(tf.arg_max(y_hot,1))

labhot

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [16]:
accuracy_score(result,labhot)

0.9933333333333333

# ================Keras Implementation=========================

In [17]:
y_hot

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [18]:
Y_label 

Species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [19]:
mymodel = tf.keras.models.Sequential([
    tf.keras.layers.Dense(50, input_dim=4 ,activation=tf.nn.relu),
    tf.keras.layers.Dense(50, activation=tf.nn.relu),
    tf.keras.layers.Dense(50, activation=tf.nn.relu),
    tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

In [23]:
mymodel.compile(optimizer ='adam',
    loss = 'categorical_crossentropy',
    metrics=['accuracy']
)

In [24]:
mymodel.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                250       
_________________________________________________________________
dense_1 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_2 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 153       
Total params: 5,503
Trainable params: 5,503
Non-trainable params: 0
_________________________________________________________________


In [33]:
# training

mymodel.fit(X_input, y_hot, epochs=7)

Epoch 1/7
150/150 [==============================] - 0s 140us/step - loss: 0.4339 - acc: 0.8933
Epoch 2/7
150/150 [==============================] - 0s 133us/step - loss: 0.4018 - acc: 0.9733
Epoch 3/7
150/150 [==============================] - 0s 127us/step - loss: 0.3769 - acc: 0.9400
Epoch 4/7
150/150 [==============================] - 0s 133us/step - loss: 0.3447 - acc: 0.9600
Epoch 5/7
150/150 [==============================] - 0s 113us/step - loss: 0.3127 - acc: 0.9600
Epoch 6/7
150/150 [==============================] - 0s 180us/step - loss: 0.2871 - acc: 0.9800
Epoch 7/7
150/150 [==============================] - 0s 167us/step - loss: 0.2578 - acc: 0.9800


In [34]:
mymodel.evaluate(X_input, y_hot)

150/150 [==============================] - 0s 60us/step


[0.24197936773300172, 0.98]