## Demo on Matrix Multiplication

link = https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable([[1,2,3],[4,5,6]])

In [3]:
y = tf.Variable([[7,8],[9,10],[11,12]])

In [4]:
init_op = tf.global_variables_initializer()

In [5]:
sess = tf.Session()

In [6]:
sess.run(init_op)

In [7]:
print(sess.run(x))

[[1 2 3]
 [4 5 6]]


In [9]:
x.shape

TensorShape([Dimension(2), Dimension(3)])

In [8]:
sess.run(y)

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

In [11]:
c1 = tf.matmul(x, y)

In [12]:
sess.run(c1)

array([[ 58,  64],
       [139, 154]])

In [13]:
c2 = tf.matmul(y, x)

In [14]:
sess.run(c2)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [15]:
sess.close()