In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
import os
os.chdir('D:/Term 3/AI/DataSet')

In [3]:
data = pd.read_csv('Iris_dataset.csv')
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
data['Species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
data['Species'] = data['Species'].map({'setosa':0,'versicolor':1,'virginica':2})
data.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
x_input = data[data.columns.difference(['Species'])]
y_label = data.iloc[:,-1]

In [7]:
x_input.head()

Petal.Length  Petal.Width  Sepal.Length  Sepal.Width
0           1.4          0.2           5.1          3.5
1           1.4          0.2           4.9          3.0
2           1.3          0.2           4.7          3.2
3           1.5          0.2           4.6          3.1
4           1.4          0.2           5.0          3.6

In [11]:
y_label.tail()

145    2
146    2
147    2
148    2
149    2
Name: Species, dtype: int64

In [10]:
y_dummies = pd.get_dummies(y_label)
y_dummies

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

In [13]:
y_hot = y_dummies.values

In [14]:
#defining the perceptron

#define placeholder for features and labels
x = tf.placeholder(tf.float32,[None,4])

y = tf.placeholder(tf.float32,[None,3])

In [15]:
#weights and bias

weight = tf.Variable(tf.truncated_normal([4,3],stddev=0.1))

bias = tf.Variable(tf.truncated_normal([1],stddev=0.1))

In [16]:
# input function

I = tf.add(tf.matmul(x,weight),bias)

In [19]:
#activation function

output = tf.nn.softmax(I)

In [6]:
# define the perceptron as end

# this section is for trainning the perceptron

In [20]:
# define the cost/loss fns and the optimizer

individual_loss = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=output)
loss = tf.reduce_mean(individual_loss)

gdo = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
train = gdo.minimize(loss)

In [21]:
#initialize the variables

init = tf.global_variables_initializer()

In [22]:
sess = tf.Session()
sess.run(init)

In [ ]:
# sess.run(train)

In [67]:
for i in range(5000):
    final_train = sess.run(train, feed_dict={x:x_input, y:y_hot})

In [68]:
result = sess.run(output, feed_dict={x:x_input})

In [69]:
#result

In [70]:
pred = sess.run(tf.argmax(result,1))
pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [71]:
orginal = sess.run(tf.argmax(y_hot,1))
orginal

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [72]:
accuracy_score(pred, orginal)

0.9733333333333334

In [73]:
confusion_matrix(pred, orginal)

array([[50,  0,  0],
       [ 0, 46,  0],
       [ 0,  4, 50]], dtype=int64)