In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable([[1,2,3],[4,5,6]])

In [3]:
y = tf.Variable([[7,8,9],[10,11,12]])

In [4]:
sess = tf.Session()

In [5]:
init_op = tf.global_variables_initializer()

In [6]:
sess.run(init_op)

In [15]:
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32_ref>

In [7]:
sess.run(x)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
y

<tf.Variable 'Variable_1:0' shape=(2, 3) dtype=int32_ref>

In [8]:
sess.run(y)

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
c1 = tf.multiply(x, y)

In [10]:
sess.run(c1)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [11]:
c2 = tf.multiply(y, x)

In [12]:
sess.run(c2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [13]:
c3 = tf.multiply(x,10)

In [14]:
sess.run(c3)

array([[10, 20, 30],
       [40, 50, 60]])

In [17]:
c3

<tf.Tensor 'Mul_2:0' shape=(2, 3) dtype=int32>

### Instead of Variable use placeholders

In [18]:
aval = [[1,2,3],[4,5,6]]
bval = [[7,8,9],[10,11,12]]

In [19]:
a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)

In [20]:
c4 = tf.multiply(a,b)

In [21]:
sess.run(c4, feed_dict={a:aval, b:bval})

array([[ 7, 16, 27],
       [40, 55, 72]])

In [22]:
sess.close()