In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable([2,50,3,10,4,5,6,7])

In [3]:
y = tf.Variable([[1,2],[3,4],[5,6]])

In [4]:
z = tf.Variable([[1,9],[8,2],[8,7]])

In [5]:
sess = tf.Session()

In [6]:
init_op = tf.global_variables_initializer()

In [7]:
sess.run(init_op)

### Shape

In [8]:
sess.run(x)

array([ 2, 50,  3, 10,  4,  5,  6,  7])

In [14]:
x.shape

TensorShape([Dimension(8)])

In [9]:
sess.run(y)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
y.shape

TensorShape([Dimension(3), Dimension(2)])

### Reshape

In [11]:
sess.run(tf.reshape(y,[2,3]))

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
sess.run(z)

array([[1, 9],
       [8, 2],
       [8, 7]])

In [13]:
z.shape

TensorShape([Dimension(3), Dimension(2)])

In [16]:
print('1--',sess.run(tf.reshape(z, [2,3])))
print('2--',sess.run(tf.reshape(z, [1,6])))
print('3--',sess.run(tf.reshape(z, [6,1])))
print('4--',sess.run(tf.reshape(z, [1,2,3])))

1-- [[1 9 8]
 [2 8 7]]
2-- [[1 9 8 2 8 7]]
3-- [[1]
 [9]
 [8]
 [2]
 [8]
 [7]]
4-- [[[1 9 8]
  [2 8 7]]]


### Max Value

In [17]:
sess.run(x)

array([ 2, 50,  3, 10,  4,  5,  6,  7])

In [18]:
sess.run(tf.argmax(x, axis=0))

1

In [19]:
sess.run(z)

array([[1, 9],
       [8, 2],
       [8, 7]])

In [20]:
sess.run(tf.argmax(z, axis=0))

array([1, 0], dtype=int64)

In [21]:
sess.run(tf.argmax(z, axis=1))

array([1, 0, 0], dtype=int64)

In [22]:
sess.close()